### ISSUE TITLE
I found some bugs

### ISSUE THREAD

**Issue by bmsuseluda** [layereight/nfc-music-box#1]
Hello @layereight thank you for your great work.
I found some bugs, but wasn't able to create a pull request. Therefore i forked your repo and added a branch there.
Please have a look: https://github.com/layereight/MFRC522-trigger/compare/master...bmsuseluda:FixSomeBugs?expand=1

**Comment by layereight** [comment]
Hi @bmsuseluda, sorry for the late reaction.

I don't see any reason why pull requests wouldn't work on the repo. Can you please try again?

Also, can you explain why `os.path.dirname(__file__)` isn't woking in your case. How and where are you running the application?

**Comment by layereight** [comment]
Hey, @bmsuseluda,

these bugs have been fixed with the latest release of https://github.com/layereight/MFRC522-trigger.
